---
version: '3'
services:

  #data:
  #  image: tianon/true
  #  container_name: scraper-data
  #  volumes:
  #  - "$PWD:/app/src"
  #  - "./shared/data:/data"
  #  - "./shared/conf.d:/app/conf.d"
  #  - "./shared/models:/opt/models"

  e3w:
    container_name: e3w
    build:
      context: .
      dockerfile: "etcdtool.alpine-dockerfile"
    # network_mode: "host"
    # hostname: e3w
    ports:
    - 8086:8086
    volumes:
    - "${PWD}:/go/src/github.com/roscopecoltran/e3w" # change it for "$PWD:/app", if you want to share the source code with the container
    - "./shared/dist:/app"
    - "./shared/conf.d/etcdtool:/data/conf.d/etcdtool"
    depends_on:
    - etcd1
    - etcd2
    - etcd3
    links:
    - etcd1
    - etcd2
    - etcd3
    working_dir: /app
    command: ["/bin/bash"]
    # command: ["/app/e3w"]

  etcd1:
    container_name: etcd-1
    image: quay.io/coreos/etcd:v3.1.10
    entrypoint: /usr/local/bin/etcd
    # extra_hosts:
    #   - "dockerhost:$DOCKERHOST"
    hostname: etcd1
    environment:
    - ETCD_DATA_DIR=/data
    volumes:
    - ./shared/data/etcd:/data
    command:
    - '--name=etcd-1'
    - '--initial-advertise-peer-urls=http://etcd-1:2380'
    - '--listen-peer-urls=http://etcd-1:2380'
    - '--listen-client-urls=http://etcd-1:2379,http://localhost:2379'
    - '--advertise-client-urls=http://etcd-1:2379'
    - '--initial-cluster-token=mys3cr3ttok3n'
    - '--heartbeat-interval=250'
    - '--election-timeout=1250'
    - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
    - '--initial-cluster-state=new'

  etcd2:
    container_name: etcd-2
    image: quay.io/coreos/etcd:v3.1.10
    entrypoint: /usr/local/bin/etcd
    # extra_hosts:
    #   - "dockerhost:$DOCKERHOST"
    hostname: etcd2
    environment:
    - ETCD_DATA_DIR=/data
    volumes:
    - ./shared/data/etcd:/data
    command:
    - '--name=etcd-2'
    - '--initial-advertise-peer-urls=http://etcd-2:2380'
    - '--listen-peer-urls=http://etcd-2:2380'
    - '--listen-client-urls=http://etcd-2:2379,http://localhost:2379'
    - '--advertise-client-urls=http://etcd-2:2379'
    - '--initial-cluster-token=mys3cr3ttok3n'
    - '--heartbeat-interval=250'
    - '--election-timeout=1250'
    - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
    - '--initial-cluster-state=new'

  etcd3:
    container_name: etcd-3
    image: quay.io/coreos/etcd:v3.1.10
    entrypoint: /usr/local/bin/etcd
    hostname: etcd3
    # extra_hosts:
    #   - "dockerhost:$DOCKERHOST"
    environment:
    - ETCD_DATA_DIR=/data
    volumes:
    - ./shared/data/etcd:/data
    command:
    - '--name=etcd-3'
    - '--initial-advertise-peer-urls=http://etcd-3:2380'
    - '--listen-peer-urls=http://etcd-3:2380'
    - '--listen-client-urls=http://etcd-3:2379,http://localhost:2379'
    - '--advertise-client-urls=http://etcd-3:2379'
    - '--initial-cluster-token=mys3cr3ttok3n'
    - '--heartbeat-interval=250'
    - '--election-timeout=1250'
    - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
    - '--initial-cluster-state=new'
